### ISSUE TITLE
Error: You must provide at least one key to the has

### ISSUE THREAD

**Issue by serine** [ctlab/fgsea-web#2]
@assaron just FYI regarding my previous issue mentioned [here](https://github.com/ctlab/fgsea/issues/33) it errors out [here](https://github.com/ctlab/fgsea-web/blob/3dd3e8bd2f91063ebf77e85ad4cce08345d09341/server.R#L143) if no enrichment was found, so better error handling needed I guess. 

My other issue was [here](https://github.com/ctlab/fgsea-web/blob/3dd3e8bd2f91063ebf77e85ad4cce08345d09341/functions.R#L127). In my current shiny app that just runs bash wrapper around `gsea` I make user to specify "stat" column. Guessing is fine, but it wasn't working with my output. 

Cheers

**Comment by assaron** [comment]
We abandoned this app for a while, so likely we won't fix it. Keeping the issue open though, just in case.

**Comment by serine** [comment]
great, thanks for that. I'll close this issue no need to keep it open. This was mainly FYI. I'll continue on with my fork. thanks
